### PR TITLE
Added/fixed feature types

### PR DESCRIPTION
**Pull request by solenevEPAM**
Regarding the issue: https://github.com/TeselaGen/ve-sequence-parsers/issues/4

### CODE REVIEW

**Comment by solenevEPAM** [comment]
Hi, 
gotta say that a test run fails on master as well.
I've solved that on my machine by 'npm install ve-range-utils' (because it's what is missing looks like)

Or do I misunderstood something?

Thanks in advance

**Comment by solenevEPAM** [comment]
@tnrich 
if you run 'npm test' in master, it will throw an error 
`Error: Cannot find module 've-range-utils'`
So, i've added ve-range-utils as dependecy

**Comment by mfero** [comment]
@solenevEPAM Thomas is on vacation this week with his family, I'm sure he will respond when he comes back online perhaps later this week ;)

**Comment by solenevEPAM** [comment]
@tnrich @mfero Could you check the pull request, please?

**Comment by tnrich** [comment]
Hey @solenevEPAM sorry I didn't respond to this sooner. I've intentionally not included ve-range-utils as a hard dependency because I was finding that it made it more cumbersome to get all of my packages on the same version in the larger projects. I would have have multiple versions of ve-range-utils showing up in my build. 

I'll add it as a peer dependency here so people know to install it to use this module and add in the other changes included in the PR.

**Comment by solenevEPAM** [comment]
Fixed in version 4.3.2

**Pull request closed without merging**
