### PR TITLE
 add VERSION on Genbank

### PR DESCRIPTION
**Pull request by linediconsine**
I start to add some missing headers value on the Genbank

This is the first
VERSION
documented here
https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html#VersionB
https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html

### CODE REVIEW

**Comment by linediconsine** [comment]
About accession from docs 
Accession is 
"The unique identifier for a sequence record. An accession number applies to the complete record and is usually a combination of a letter(s) and numbers, such as a single letter followed by five digits (e.g., U12345) or two letters followed by six digits (e.g., AF123456). Some accessions might be longer, depending on the type of sequence record."

Reference : https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html#AccessionB

**Comment by tnrich** [comment]
@linediconsine awesome looks like a good start! Do you also want to add some code to pull that data off of genbank files when converting them to JSON?

**Comment by linediconsine** [comment]
Hi @[tnrich](https://github.com/tnrich) 
Please check this PR
- I had to disable a snapgeneToJson.test_disable.js
- Update some libraries ( Vulnerabilities wen from 111 to 20)
- Accession is now also in jsonToGenbank

**Comment by tnrich** [comment]
@linediconsine this landed in v8.3.27 

Thanks!

**Pull request merged**
