### PR TITLE
fixed parsing sentences from feature note in genbank files

### PR DESCRIPTION
**Pull request by grigoll**
Hi there @tnrich,
This pull request is for a minor parsing issue with a feature note. There was no space in between the last word of the current line and the first word of the next line, after parsing a feature note in genbank file. E.g.:
```
/note="This inhibition can be relieved by adding lactose or
isopropyl-beta-D-thiogalactopyranoside"
```
was parsed as
```
{"note":"This inhibition can be relieved by adding lactose orisopropyl-beta-D-thiogalactopyranoside"}
```

### CODE REVIEW

**Comment by tnrich** [comment]
Hey @grigoll ! Thanks for finding and fixing this bug. If you could just add a test case for your fix then I'd be more than happy to merge it in. 

My only question is are feature notes of type "note" the only type that requires this special multi-line sentence logic?  Do feature notes of another type, say type==="comment" also need that multi-line logic? 

Thanks!

**Comment by grigoll** [comment]
@tnrich yes, but first I need to check two failed test cases for a genbank file. Turns out genbank files can have comments in the following format too, one after another (is it considered as multiline though? 🤔):
```
/note="GENE [pBbE0k-RFP]"
/note="GENE GENE [pBbE0k-RFP]"
```
and I want to check how my fix applies to these cases.

Now about your question regarding `type==="comment"`. I'm not sure, I haven't come across a multiline comment, but I think it will be required for that too. And maybe not only for `comment` but other types, considering that the parsing logic is the same for every multiline item (might be wrong here). Finding a specific case and checking it is needed.

**Comment by grigoll** [comment]
@tnrich so I've found a much simpler fix and also added a few tests.

**Comment by tnrich** [comment]
@griggol sorry this must have gotten lost in the stack for me! I'll get this in now

**Comment by tnrich** [comment]
This will drop in bio-parsers@8.3.12

**Pull request merged**
